"""add video_scripts table

Revision ID: 69deabac3f7e
Revises: 76106014e5ac
Create Date: 2026-07-17 10:42:35.428085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69deabac3f7e'
down_revision: Union[str, Sequence[str], None] = '76106014e5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('video_idea', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('ai_model_used', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['trend_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_scripts_search_id'), 'video_scripts', ['search_id'], unique=False)
    op.drop_constraint(op.f('trend_analyses_search_id_key'), 'trend_analyses', type_='unique')
    op.drop_index(op.f('ix_trend_analyses_search_id'), table_name='trend_analyses')
    op.create_index(op.f('ix_trend_analyses_search_id'), 'trend_analyses', ['search_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_analyses_search_id'), table_name='trend_analyses')
    op.create_index(op.f('ix_trend_analyses_search_id'), 'trend_analyses', ['search_id'], unique=False)
    op.create_unique_constraint(op.f('trend_analyses_search_id_key'), 'trend_analyses', ['search_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_video_scripts_search_id'), table_name='video_scripts')
    op.drop_table('video_scripts')
    # ### end Alembic commands ###
