"""add assembled_videos table

Revision ID: dbf8e5f32f40
Revises: 533e9cd3748b
Create Date: 2026-07-17 16:09:02.811443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf8e5f32f40'
down_revision: Union[str, Sequence[str], None] = '533e9cd3748b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembled_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('narration_id', sa.UUID(), nullable=False),
    sa.Column('video_file_path', sa.Text(), nullable=False),
    sa.Column('thumbnail_file_path', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['narration_id'], ['voice_narrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assembled_videos_narration_id'), 'assembled_videos', ['narration_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assembled_videos_narration_id'), table_name='assembled_videos')
    op.drop_table('assembled_videos')
    # ### end Alembic commands ###
