"""add youtube_uploads table

Revision ID: e7f948b284ae
Revises: dbf8e5f32f40
Create Date: 2026-07-18 10:27:54.385906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f948b284ae'
down_revision: Union[str, Sequence[str], None] = 'dbf8e5f32f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.Text(), nullable=False),
    sa.Column('youtube_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['assembled_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_uploads_video_id'), 'youtube_uploads', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_uploads_video_id'), table_name='youtube_uploads')
    op.drop_table('youtube_uploads')
    # ### end Alembic commands ###
