"""add compliance safeguard columns

Revision ID: e8a921b61d6a
Revises: e7f948b284ae
Create Date: 2026-07-18 15:12:45.851163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8a921b61d6a'
down_revision: Union[str, Sequence[str], None] = 'e7f948b284ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Not autogenerated - op.add_column() does NOT create the associated
    # Postgres enum TYPE the way CREATE TABLE does (that's only automatic
    # at table-creation time). Confirmed via a real failed upgrade attempt
    # against this project's actual dev Postgres: "type review_status does
    # not exist". Must create the type explicitly before adding a column
    # that references it.
    review_status_enum = sa.Enum('pending_review', 'approved', 'rejected', name='review_status')
    review_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembled_videos', sa.Column('synthetic_content_disclosed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('video_scripts', sa.Column('review_status', review_status_enum, server_default='pending_review', nullable=False))
    op.add_column('video_scripts', sa.Column('claim_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('video_scripts', sa.Column('max_similarity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_scripts', 'max_similarity_score')
    op.drop_column('video_scripts', 'claim_sources')
    op.drop_column('video_scripts', 'review_status')
    op.drop_column('assembled_videos', 'synthetic_content_disclosed')
    # ### end Alembic commands ###
    # Not autogenerated - dropping the column does NOT drop the native
    # Postgres enum type it used, and a later upgrade would then fail with
    # "type review_status already exists" without this.
    sa.Enum(name='review_status').drop(op.get_bind(), checkfirst=True)
